name: Check Frontend
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: true
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "20"
      - name: Install
        run: yarn
        working-directory: ./frontend/code
      - name: Do a build of the frontend
        run: yarn build
        working-directory: ./frontend/code
        env:
          ESLINT_NO_DEV_ERRORS: true
      # @TODO: Figure out more ways to verify that the frontend app actually runs, e.g. in a browser
