name: Synth
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  workflow_dispatch: {}

jobs:
  synth:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: ensure correct user
        run: chown -R root /__w/cdktf-integration-serverless-example/
      - name: Install dependencies
        run: yarn
      - name: Synth
        run: yarn get && yarn synth
